language: go

go:
- master

install:
- GO111MODULE=on go get github.com/gohugoio/hugo

script:
- hugo

deploy:
  provider: pages
  skip_cleanup: true
  repo: yeya24/yeya24.github.io
  target-branch: master
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master
